### PR TITLE
Updated glue fumen

### PR DESCRIPTION
**Pull request by Marfung37**
Fix issue with missing glued fumens on significant number of duplicate of pieces

### CODE REVIEW

**Comment by Marfung37** [comment]
Has failing case of v115@DhAti0EeBtR4g0EeAtR4RpHeRpJeAgH

**Comment by Marfung37** [comment]
Determine due to Z considered to be floating as it is found first before S is placed

**Comment by Marfung37** [comment]
Reverting to original before adding checking for floating piece

**Comment by Hillosanation** [comment]
thanks!

**Pull request merged**
